batctl: Work around musl conflicts with linux/ethtool.h
linux/ethtool.h and musl's net/ethernet.h cannot be used at the same time.
Otherwise the compiles failes with

    In file included from include/net/ethernet.h:10:0,
                     from functions.h:25,
                     from ioctl.c:36:
    include/netinet/if_ether.h:101:8: error: redefinition of 'struct ethhdr'
     struct ethhdr {
            ^
    In file included from include/linux/ethtool.h:17:0,
                     from ioctl.c:33:
    include/linux/if_ether.h:140:8: note: originally defined here
     struct ethhdr {
            ^
    Makefile:123: recipe for target 'ioctl.o' failed

Fixes: 894b25c2be5f ("batctl: Make root privileges check function specific")
Signed-off-by: Sven Eckelmann <sven@narfation.org>